#!/bin/zsh

VPN_PROFILE_LIST=/tmp/list_vpn_profile.txt
PRITUNL_CLIENT=`locate pritunl-client | head -n1`

# update profile list metadata
$PRITUNL_CLIENT list | grep -v ID | awk -F "|" '{print $2}' | xargs -n1 > $VPN_PROFILE_LIST

# stop all vpn profile
for a in `cat $VPN_PROFILE_LIST`
do
echo "stopping pritunl vpn profile id $a"
$PRITUNL_CLIENT stop $a
done
